export enum ErrorCodes {
  BAD_REQUEST = 'BAD_REQUEST',
  CLIENT_CLOSED_REQUEST = 'CLIENT_CLOSED_REQUEST',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  METHOD_NOT_SUPPORTED = 'METHOD_NOT_SUPPORTED',
  NOT_FOUND = 'NOT_FOUND',
  PARSE_ERROR = 'PARSE_ERROR',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  PRECONDITION_FAILED = 'PRECONDITION_FAILED',
  TIMEOUT = 'TIMEOUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
