import Head from 'next/head';
import type { NextPage } from 'next';

import { HomeComposition } from 'compositions/home';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Simon Stepien Full Stack Developer</title>
      <meta name='description' content='Generated by create-t3-app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <HomeComposition />
  </>
);

export default Home;
